[colors]
foreground = "#c0caf5"
background = "#1a1a1a"
cursor_bg = "#c0caf5"
cursor_border = "#c0caf5"
cursor_fg = "#1a1a1a"
selection_bg = "#283350"
selection_fg = "#c0caf5"
split = "#7aa2f7"
compose_cursor = "#ff9e64"
scrollbar_thumb = "#292e42"

ansi = ["#151515", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#a9b1d6"]
brights = ["#414868", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#c0caf5"]

[colors.tab_bar]
inactive_tab_edge = "#161616"
background = "#1a1a1a"

[colors.tab_bar.active_tab]
fg_color = "#161616"
bg_color = "#7aa2f7"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#292e42"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#7aa2f7"
bg_color = "#292e42"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#7aa2f7"
bg_color = "#1a1a1a"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#7aa2f7"
bg_color = "#1a1a1a"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_night"